### ISSUE TITLE
Unable to assume the service linked role. Please verify that the ECS service linked role exists.

### ISSUE THREAD

**Issue by krystofbe** [tree-schema/tree-schema-ecs-example#3]
I get this error in when creating the services

```
Unable to assume the service linked role. Please verify that the ECS service linked role exists.
```

do i need to add other roles?

**Comment by krystofbe** [comment]
added this to the `Resources` block:

```
  ECSServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: ecs.amazonaws.com
```
